name: C201

on:
  push:
    branches:
      - c201-v2
      - c201-testing

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y --no-install-recommends gcc-arm-linux-gnueabihf vboot-kernel-utils u-boot-tools device-tree-compiler ccache cgpt qemu-user-static binfmt-support
        curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o vercmp -
        sudo install -m 755 vercmp /usr/local/bin/vercmp
        sudo install -D -m 644 woof-code/rootfs-skeleton/usr/local/petget/categories.dat /usr/local/petget/categories.dat
        mkdir -p local-repositories
        ln -s `pwd`/local-repositories ../local-repositories
        echo "dash dash/sh boolean false" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
        ccache --set-config=hash_dir=false --set-config=max_size=5.0G
        sudo ln -s /usr/bin/mount /usr/local/bin/mount-FULL
    - name: Cache local-repositories
      id: cache-local-repositories
      uses: actions/cache@v2
      with:
        path: local-repositories
        key: local-repositories-${{ github.sha }}
        restore-keys: |
          local-repositories-
    - name: Fix cache ownership
      run: sudo chown -R root:root local-repositories
    - name: Download packages
      run: |
        (echo 1; echo 1; echo; echo) | sudo -E ./merge2out
        cd ../woof-out_x86_64_arm_debian_bullseye
        sudo ./0setup
        sudo ./1download
    - name: Cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-${{ github.sha }}
        restore-keys: |
          ccache-
    - name: Build kernel
      run: |
        cd ../woof-out_x86_64_arm_debian_bullseye/kernel-kit
        sudo cp -f c201-build.conf build.conf
        sudo -E ./build.sh
    - name: Build image
      run: |
        cd ../woof-out_x86_64_arm_debian_bullseye
        echo | sudo ./2createpackages
        sudo -E ./3builddistro
        sudo gzip -1 ./woof-output-bullseye-8.0/bullseye-8.0-ext4-2gb.img
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ github.run_number }}
        release_name: v${{ github.run_number }}
        draft: false
        prerelease: true
    - name: Upload C201 image
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ../woof-out_x86_64_arm_debian_bullseye/woof-output-bullseye-8.0/bullseye-8.0-ext4-2gb.img.gz
        asset_name: bullseye-8.0-ext4-2gb.img.gz
        asset_content_type: application/octet-stream
    - name: Upload C201 devx
      id: upload-devx
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ../woof-out_x86_64_arm_debian_bullseye/woof-output-bullseye-8.0/devx_bullseye_8.0.sfs
        asset_name: devx_bullseye_8.0.sfs
        asset_content_type: application/octet-stream